# PostgreSQL Config
server.port=8088
spring.datasource.url=jdbc:postgresql://localhost:5432/spendify
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect


# JWT Secret Key
jwt.secret=abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()-_=+[]{}|;:'",.<>?/`~
jwt.expiration=86400000  # 1 day (in milliseconds)